### ISSUE TITLE
ATLConversationViewController in TabBar - Keyboard Won't Appear

### ISSUE THREAD

**Issue by cdstamper** [layerhq/Atlas-iOS#817] opened 2015-05-06 21:02 UTC
I'm presenting the ConversationListViewController copied verbatim from the Layer+Parse example, as a tab in my tab bar controller (ConversationListViewController is wrapped in a NavigationController, configured in storyboard). TabBar->NavController->ConversationListViewController, essentially.

I am hiding the bottom bar when pushing an individual conversation view (leaving it visible in the conv list view), using hidesBottomBarWhenPushed. Works perfectly.

However, when moving to the conversation view to either compose a new conversation, or continue an existing one, the keyboard will not appear when tapping on either in the message field, or the 'to' field. Instead, the cursor appears in both the To field and the Message field, simultaneously.

This only happens when wrapped inside a tab bar controller.

Possibly related to #754

**Comment by kcoleman731** [comment] 2015-05-07 19:47
@cdstamper this is happening on an actual device or in the simulator?

**Comment by cdstamper** [comment] 2015-05-07 19:51
Both. 

- In the simulator, I can't even use my physical hardware keyboard to enter text. 

- On device, the fields receive focus (simultaneously as I mentioned), but the keyboard does not appear.

**Comment by cdstamper** [comment] 2015-05-12 19:59
@kcoleman731 any idea how to fix this?

**Comment by kmahal** [comment] 2015-05-13 21:31
@cdstamper I couldn't reproduce this programatically.  Could we have a look at your implementation files to verify there's nothing out of place?

**Comment by kmahal** [comment] 2015-06-24 23:44
@cdstamper any update on this item?  If not we'll close it out since we haven't been able to reproduce it.

**Comment by cdstamper** [comment] 2015-06-24 23:50
Let's close it. The project went stagnant so I haven't been able to look further into, but it is still an issue.

**Closed** 2015-06-24 23:59 UTC

**Comment by khanhvu161188** [comment] 2015-08-04 15:13
I meet same issue here when go from push notification.
Let's talk my app have main UITabbarController. 1 tab is for list all conversation and when i tap on an conversation it will push to view for conversation.On this page, if show keyboard for input something and i quit app (back to home). If i receive a push notification pointing to another previous conversation that i was typing, it will direct me to new conversation but MessageInputToolbar don't show any more
