### ISSUE TITLE
Wrong avatar image showing in conversation list view

### ISSUE THREAD

**Issue by DevMoz** [layerhq/Atlas-iOS#986] opened 2015-09-30 00:03 UTC
Hi there,

In my app, I have avatars showing beside each conversation in my ATLConversationListViewController subclass. The avatar is the other participants profile photo (retrieved from a URL on the conversation's meta data). My custom AvatarItem class adopts the ATLAvatarItem protocol. I return an AvatarItem in the following data source method

`- (id<ATLAvatarItem>)conversationListViewController:(ATLConversationListViewController *)conversationListViewController avatarItemForConversation:(LYRConversation *)conversation;`

I set the following property in my AvatarItem class:

`@property (nonatomic, readonly) NSURL *avatarImageURL;`

This works well the majority of the time; however, on some occasions when I run the app, I'll see the wrong avatar image displayed with the wrong conversation cell. This doesn't happen often. When I tap on a cell that shows the the wrong avatar image, transition into the ConversationViewController, then transition back; the wrong image is replaced by the correct image. The problem only seems to happen when the app is launched. 

I'm a bit of novice, so apologies if I'm doing something wrong here. I'm at a loss as to why / how this happens.

**Comment by kmahal** [comment] 2015-10-06 05:25
@DevMoz Thanks for bringing it up.  Unfortunately I haven't been able to reproduce the problem- does this happen after scrolling?  Or even when loading it from a URL for a cell in the visible window?

**Comment by DevMoz** [comment] 2015-10-07 03:25
@kmahal Thank you for your reply. Appreciated. Hopefully the following detail is helpful. 

The problem seems mostly isolated to fresh installs. 

I created 20 test conversations with a letter of the alphabet as the conversation title and an image of the letter as the associated avatar.

You can see in the first image (from a fresh install immediately upon launch) that some of the avatar images don't match the conversation and are duplicated. (n,p,l,f)

![img_0179](https://cloud.githubusercontent.com/assets/6776567/10328306/cb70abf8-6c67-11e5-8f4f-a44619d418a4.png)


Then when I tap into a conversation and transition back (conversation title 'p') the correct image is now shown. 

![img_0180](https://cloud.githubusercontent.com/assets/6776567/10328320/d19b4e2a-6c67-11e5-894c-6c6be9ed20f2.png)


If I then kill the app, run it again (without a re-installing), everything seems to work fine:

![img_1125](https://cloud.githubusercontent.com/assets/6776567/10328322/d5102fbc-6c67-11e5-869f-70b644056fcf.png)

Please let me know if I can provide more detail. I've tried digging into the code but I cannot discern any reason why it works normally 95% of the time but not the other 5%.

**Comment by kmahal** [comment] 2015-10-12 23:11
@DevMoz try to debug this with just 2 conversations and looking at the `downloadTask` information to see if the cell is being updated incorrectly.  I'm not able to reproduce this so unfortunately can't be of more help here.

**Comment by DevMoz** [comment] 2015-10-14 23:06
Thanks @kmahal. I reduced it down to two conversations and am still able to reproduce the issue:

![simulator screen shot oct 14 2015 3 53 36 pm](https://cloud.githubusercontent.com/assets/6776567/10500264/cd803aa6-728b-11e5-9c23-a10b3494635f.png)

I noticed with two conversations, `cellForRowAtIndexPath` in `ATLConversationListViewController` is called a total of four times. When it works normally, `fetchImageFromRemoteImageURL:remoteImageURL` in `ATLAvatarImageView.m` is also called four times . Occasionally, `fetchImageFromRemoteImageURL:remoteImageURL` is only called three times which is when the wrong image appears.

Could the issue be with the following image caching code in: `loadAvatarImageWithURL:imageURL`
```
  __block NSString *stringURL = imageURL.absoluteString;
    UIImage *image = [[[self class] sharedImageCache] objectForKey:stringURL];
    if (image) {
        self.image = image;
        return;
    }
```

**Comment by kcoleman731** [comment] 2015-11-06 00:36
@kmahal any updates on this?

**Comment by MatthewAnthonyBordas** [comment] 2015-11-07 10:49
I am also experiencing this same issue with incorrect avatar images showing in the conversation list view!

**Comment by MatthewAnthonyBordas** [comment] 2015-11-22 00:36
@kmahal ?

**Comment by DevMoz** [comment] 2015-12-03 02:10
Any update on this? I'm still having the same issue and haven't been able to diagnose it on my own. My testers are noticing the same problem and it's an impediment to launching the app. Please let me know how I can help. 

In this example, the wrong avatar image is being displayed along with the users initial. It acts exactly as described above. If I tap into the conversation with the wrong image, then exit out, the avatar image is gone and only the initial remains.

![img_0105](https://cloud.githubusercontent.com/assets/6776567/11549907/359aabb2-991f-11e5-8c2b-5c06b5ec6c01.png)

**Comment by DevMoz** [comment] 2016-04-24 22:40
Just wondering if this is something worth looking at. Despite trying to solve this on my own and contribute, I've been unable. It's a fairly persistent problem that's caused test users to message the wrong individuals as they've selected conversations based on incorrect photos. Please let me know what other info I can provide. From the thread, there is at least one other individual experiencing the same issue...Perhaps there are others...

![img_0503](https://cloud.githubusercontent.com/assets/6776567/14770969/420d8a7a-0a32-11e6-8c4b-595b82835e1c.png)

**Comment by kcoleman731** [comment] 2016-05-02 19:47
Hi @DevMoz sorry for the delay here. I am going to have a look at this for you. Will get back with my findings.

**Comment by kcoleman731** [comment] 2016-05-02 21:33
Hi @DevMoz I just investigated on my side and cannot seem to repro. What version of Atlas are you using?
 
To attempt the repro, I am returning a URL from `Placehold.it` with the first name of the user as the text in the image. So for my conversation with Heather for example, the `avatarImageURL` is `http://placehold.it/350x150?text=Heather`. In the attached image, you can see that all of the images line up. Would you mind trying this approach in your app?

Have you tried logging the `avatarImageURL`s for your cells as they come on screen to make sure you are fetching the correct one? Additionally, I'm not sure if you have seen the new `LYRIdentity` object in `LayerKit`, but this allows you to provide Layer with the avatar image URL for you users, and we handle putting it on screen for you. 

![screen shot 2016-05-02 at 2 28 29 pm](https://cloud.githubusercontent.com/assets/1423931/14968658/c39535fc-1072-11e6-970d-99fdfe776aea.png)

**Comment by kcoleman731** [comment] 2016-05-23 16:42
@DevMoz closing this issue for now as it does not appear to be an issue any longer. Let me know if you need to reopen.

**Closed by kcoleman731** 2016-05-23 16:42 UTC

**Comment by DevMoz** [comment] 2016-05-23 17:27
Hi Kevin.

Apologies for the delay here.  

In the following test I have 7 conversations. 6 avatar items should contain an image via url and one displays the users initials:

When it loads correctly it looks like:

![img_0527](https://cloud.githubusercontent.com/assets/6776567/15478567/f568cd10-20cf-11e6-9c98-b56c4766556f.png)

As mentioned above, `cellForRowAtIndexPath` is getting called twice in `ATLConversationListViewController` (when it loads and before any scrolling). Not sure if that's a problem. In any case, when it works, the conversations appear on screen and the names (with the correct associated URLs) logged are in the same order as shown on screen like so:

Jim
Bob
Bill
Steve
Ryan
Sam

Jim
Bob
Bill
Steve
Ryan
Sam

The following is what it looks like when this loads incorrectly. Notice there is an avatar image in the only cell on screen that shouldn't contain any image.  It still happens even when every cell should contain an image.

![img_0526](https://cloud.githubusercontent.com/assets/6776567/15478580/0600026a-20d0-11e6-8cc3-5918fe1808db.png)

The logs show a different order:

Bob
Bob
Steve
Jim
Steve
Jim

Bill
Bill
Ryan
Sam
Ryan
Sam

I'm storing the URL in the conversation's metadata. My `AvatarItem` class simply checks the metadata for the presence of a URL and if none, sets the `avatarInitials` property.

I've noticed that when the app launches and a user logs in, the cells in `ATLConversationListViewController` have a cascading animation as they appear on screen one by one in quick succession. This is generally when the problem occurs. 

If you simply kill the app, then relaunch it, the cells all appear at the same time with usually no problems.  

Not sure if this helps. Happy to let this drop if you think the problem is with my own implementation. 

Thanks!
