### ISSUE TITLE
Login and Logout

### ISSUE THREAD

**Issue by LukeDurrant** [layerhq/Atlas-iOS#1367] opened 2017-03-16 06:30 UTC
Getting Unknown error calling sqlite3_step (10: disk I/O error) rs after logging in and then logout out for a user.
Looks like the database gets trashed as you have to delete the app to fix it.

**Comment by jpmcglone** [comment] 2017-04-17 21:42
Not that this should matter, but when you get this error, are you extremely low on disk space?

**Comment by LukeDurrant** [comment] 2017-04-18 00:40
I'll check

**Comment by apcrompton** [comment] 2017-09-10 23:50
I am experiencing this same issue (stacktrace below). I have reproduced the crash both on a 32GB iPhone 7 with plenty of free disk space (6.5GB free) as well as on the iOS simulator.

2017-09-05 15:28:05.847392+1000 lyf[2627:1070881] Unknown error calling sqlite3_step (10: disk I/O error) rs
2017-09-05 15:29:19.344761+1000 lyf[2627:1070881] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '`userID` cannot be nil.'

**Comment by daniel-maness** [comment] 2017-09-11 04:45
Fixed in LayerKit v0.26.9 with `IOS-3101`
https://github.com/layerhq/releases-ios/blob/master/CHANGELOG.md#0269

**Closed by daniel-maness** 2017-09-11 04:45 UTC
