### ISSUE TITLE
ConversationViewController ios 9: CollectionView Content Inset incorrect

### ISSUE THREAD

**Issue by MatthewAnthonyBordas** [layerhq/Atlas-iOS#1032] opened 2015-10-18 23:16 UTC
![screen shot 2015-10-18 at 4 15 04 pm](https://cloud.githubusercontent.com/assets/7369954/10567263/8224f22e-75b3-11e5-804c-c1bf7a99bb82.png)

![img_1321](https://cloud.githubusercontent.com/assets/7369954/10567267/94cee858-75b3-11e5-87f5-85f9ad91d50d.png)

I fixed this in my own code by setting the content inset of the top to 60, but I just wanted to make sure everyone got the fix too.

**Comment by kmahal** [comment] 2015-10-19 16:58
@MatthewAnthonyBordas feel free to submit a PR for this issue.

**Comment by MatthewAnthonyBordas** [comment] 2015-11-07 20:41
@kmahal Ok thanks!

**Comment by kmahal** [comment] 2015-11-18 07:42
@MatthewAnthonyBordas this should have been fixed in the last release.  Let me know if you're still seeing this issue.  If not we can close this ticket out.

**Comment by MatthewAnthonyBordas** [comment] 2015-11-22 00:45
It appears to be fixed but at the expense of the appearance because now the messages noticeably drop down upon presentation
![contentinset](https://cloud.githubusercontent.com/assets/7369954/11321337/37f57cce-906f-11e5-8383-2b0efadac0c2.gif)

**Comment by kmahal** [comment] 2015-11-30 23:55
@MatthewAnthonyBordas can you reproduce this issue with Atlas Messenger?  https://github.com/layerhq/Atlas-Messenger-iOS.  I'm not able to reproduce this issue.

**Closed** 2015-12-22 00:17 UTC
