### ISSUE TITLE
message is truncated ATLConversationViewController subclass on iOS 7 devices

### ISSUE THREAD

**Issue by haemi** [layerhq/Atlas-iOS#991] opened 2015-10-02 11:50 UTC
On my iOS 7 device, the text in the bubbles gets truncated (ends with three dots) most of the time. In iOS 9 this works as expected.

Am I doing anything wrong or is this a known issue?

**Comment by kmahal** [comment] 2015-10-06 05:38
@haemi We haven't seen this issue so far.  Can you provide a screenshot?

**Comment by haemi** [comment] 2015-10-06 07:15
first image: iOS 7
second image: iOS 9

immediately after sending the message it is displayed correctly, but when I out and back into the conversation, I see the truncated one.

![img_0004](https://cloud.githubusercontent.com/assets/183958/10302234/a3acfa52-6c0a-11e5-8e5f-18554ad45ac1.PNG)
![img_5187](https://cloud.githubusercontent.com/assets/183958/10302233/a3a95398-6c0a-11e5-8ec8-2953d901f845.PNG)

**Comment by kmahal** [comment] 2015-10-08 20:08
@haemi feel free to submit a pull request if you have a solution to this issue as we cannot reproduce it.  As an aside, in the coming weeks we will be also be dropping official support for ios7 as we move to dynamic frameworks.

**Comment by kmahal** [comment] 2015-10-16 00:00
@haemi with Atlas now released as a dynamic framework we no longer officially support ios7, so I will be closing this issue out.

**Closed by kmahal** 2015-10-16 00:00 UTC
