### ISSUE TITLE
ATLConversationViewController in TabBar - MessageInputToolbar Won't Appear

### ISSUE THREAD

**Issue by khanhvu161188** [layerhq/Atlas-iOS#912] opened 2015-08-04 15:21 UTC
I meet same issue #817  when go from push notification.
Let's talk my app have main UITabbarController. 1 tab is for list all conversation and when i tap on an conversation it will push to view for conversation.On this page, if show keyboard for input something and i quit app (back to home). If i receive a push notification pointing to another previous conversation that i was typing, it will direct me to new conversation but MessageInputToolbar don't show any more

**Comment by kmahal** [comment] 2015-09-22 17:35
@khanhvu161188 is this issue still occurring?  You must hide the tab bar when presenting the `ATLConversationViewController`.

**Comment by khanhvu161188** [comment] 2015-09-22 17:40
@kmahal  we still didn't not resolve this issue. What do you mean about "hide the tab bar" when present `ATLConversationViewController` ? What factor affect on this issue, currently tabbar is rootController of our app. And you want me to edit on event `ViewDidDisapear`?  or kill this controller and make `ATLConversationViewController` as rootController ? Please help us on it sir. Thanks so much

**Comment by kmahal** [comment] 2015-09-22 17:57
@khanhvu161188 use this in your `ATLConversationViewController` subclass:
```objc
-(BOOL)hidesBottomBarWhenPushed
{
    return YES;
}
```
when receiving a push notification, are you presenting the controller with animation, or without?

**Comment by khanhvu161188** [comment] 2015-09-22 18:09
@kmahal 

```
self.window.rootViewController = self.tabBarController;
                self.tabBarController.selectedIndex = 3;
                Conversation *conversationViewController = [Conversation conversationViewControllerWithLayerClient:self.layerClient];
                conversationViewController.conversation = conversation;
                conversationViewController.displaysAddressBar = NO;
                conversationViewController.hidesBottomBarWhenPushed = YES;
                [targetNavController pushViewController:conversationViewController animated:NO];
```

`Conversation` is subclass of `ATLConversationViewController `

**Comment by khanhvuNOIS** [comment] 2015-09-23 04:55
I can represent it here so that you can help me sir:
receive push=> tap on it=> return to main tab bar => navigate to list conversation => navigate to correct converastion 

And @kmahal i found that this issue only occur when i open keyboard before leave the app.
Its mean if i open conversation but not show keyboard => leave app => receive push=> tap on it=> go to conversation => work normal
but if open conversation and show keyboard=> leave app => receive push=> tap on it=> go to conversation => Error

**Comment by kmahal** [comment] 2015-09-30 00:41
@khanhvu161188 in your `viewDidAppear` of your `ATLConversationViewController` subclass if you add the following it should work:
```objc
    if (!self.view.isFirstResponder) {
        [self.view becomeFirstResponder];
    }
```
Let me know if this helps.

**Comment by kmahal** [comment] 2015-10-06 05:26
@khanhvu161188 did the above suggestion not work?  Let me know or else I'll close out this item. Thanks.

**Comment by khanhvu161188** [comment] 2015-10-07 06:49
@kmahal  sorry but it not work sir.
I'm trying another tool here https://github.com/jessesquires/JSQMessagesViewController
and it work. i'm checking what is different so that can fix on atlas. Sorry because i'm newbie on iOS , just work on backend side before so i didn't have more experience on objC for helping u

**Comment by chlebta** [comment] 2015-10-12 10:06
@kmahal I've a hidden tabBar in `ConversationController`. The problem is that once the keyboard is displayed and then dismissed the `messageToolBar` is not anymore sticked to the bottom of screen : 
![sans titre](https://cloud.githubusercontent.com/assets/1204608/10425614/daf94ad6-70d0-11e5-80dc-bbec74f8076c.png)

The space between the `messageToolBar` and `BottomView` is the hidden TabBar.

**Comment by chlebta** [comment] 2015-10-15 10:18
@khanhvu161188 did you successed to layerKit with JSQMessagesViewController

**Comment by MrMonkeyBrains** [comment] 2015-10-16 05:46
Has anyone successfully gotten Atlas' ATLConversationViewController to work as one of the views in a UITabBarController? This seems to be my problem as well.

**Comment by khanhvu161188** [comment] 2015-10-16 06:07
@chlebta actually i'm using jsqmessage now after lost many time with atlas!Atlas is good but it need to improve too much for bug fixing and performance!i'm hoping Atlas team will release newer version that resolve our problem
@MrMonkeyBrains what is your problem sir?You fade issues on input toolbar?

**Comment by MrMonkeyBrains** [comment] 2015-10-16 06:11
@khanhvu161188 I have my subclass of ATLConversationViewController as a tab in a UITabBarController (with the tab bar hidden). When the user swipes to the ConversationViewController, the messageInputToolbar is not visible. The user must swipe up to expose the messageInputToolbar.

Once the user swipes up, the messageInputToolbar is properly docked to the bottom of the view, even after sending a message and dismissing the keyboard.

The problem is that the messageInputToolbar is not visible when the ConversationViewController is first shown to the user.

**Comment by MrMonkeyBrains** [comment] 2015-10-16 06:11
@khanhvu161188 I've uploaded a gif to show the issue (problem 1) here: https://github.com/layerhq/Atlas-iOS/issues/1024

**Comment by khanhvu161188** [comment] 2015-10-16 06:17
@MrMonkeyBrains i don't remember exactly this bug but i saw it before!when i tried to debug, value of keyboard height should be 0 instead of 43px!

**Comment by MrMonkeyBrains** [comment] 2015-10-16 06:35
@khanhvu161188 ahhhh! been fighting with this for so long. i feel like i'm so close but i've tried to log and adjust keyboardheight everywhere i could find in the atlas code and i can't seem to get the toolbar to show up w/o swiping up. if you happen to remember any more of where to look in the code i'd really appreciate it.

**Comment by chlebta** [comment] 2015-10-16 07:48
@khanhvu161188 could you share that on Github, JSQMessage+Atlas, it will be great thanks.
Also, I totally agree with you Atlas is good but it needs more improvement and more support from layer team

**Comment by chlebta** [comment] 2015-10-16 07:50
@MrMonkeyBrains I got the same issue, you could fix it by disabling JQKeyboard for the conversationController

**Comment by MrMonkeyBrains** [comment] 2015-10-16 16:14
@chlebta I've tried disabling as well as removing IQKeyboard entirely - it fixes my 2nd problem (the bounce after hiding the keyboard) but not my 1st problem -- showing the input toolbar when the user gets to the conversation view

**Comment by chlebta** [comment] 2015-10-17 05:10
If you are talking about inputAccessoryView i got same issue one I figure
the problem I Will informe you

**Comment by chlebta** [comment] 2015-10-18 22:00
@khanhvu161188  any update please ?

**Comment by MrMonkeyBrains** [comment] 2015-10-19 04:46
Ok... the issue appears to stem from an issue with UIPageViewController when using Scroll type.

Use this drop-in replacement for UIPageViewController and it appears to work well: https://gist.github.com/paul-delange/5582394

**Comment by khanhvu161188** [comment] 2015-10-19 06:11
@chlebta  sorry for late response sir. Actually our project here is private project so we cannot share too much cause of NDA contract. I will try to release another version on github later when i have enough free time

**Comment by chlebta** [comment] 2015-10-26 08:01
@khanhvu161188 No problem sir,  can you provide me with your contact information I got some question if you don't mind.

**Comment by kmahal** [comment] 2015-11-18 07:38
@khanhvu161188 I'm going to close this issue out as we are not able to reproduce this issue, and we do not provide support for 3rd party keyboards.  Let me know if there are an other Atlas specific issues or if you have a PR to fix any other behavior and we can re-open this issue.

**Closed by kmahal** 2015-11-18 07:38 UTC
